contact:
  phone_number:
  email: gbest@fullerton.edu
  vcard_path: /assets/gabriela best phd.vcf
site:
  vitae_path: /assets/CV_February_2017_S.pdf
  csuf_url: 'http://business.fullerton.edu/Department/Economics/?ID=BestGabr#EconomicsFacultyInfo?user=gbest'
